[env]
TERM = "alacritty"

[general]

[window]
decorations = "Buttonless"
opacity = 1.0
startup_mode = "Windowed"

[font]
size = 25.0
normal = { family = "Codelia", style = "Regular" }
bold = { family = "Codelia", style = "Regular" }
italic = { family = "Codelia", style = "Regular" }
bold_italic = { family = "Codelia", style = "Regular" }

# sonokai.toml: Sonokai color scheme for Alacritty.
[colors.primary]
foreground = "#e2e2e3"
background = "#2c2e34"

[colors.normal]
black = "#181819"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"

[colors.bright]
black = "#7f8490"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"

[colors.cursor]
text = "#2c2e34"
cursor = "#e2e2e3"

[colors.selection]
text = "CellForeground"
background = "#414550"
